spring:
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 8
        min-idle: 2
    timeout: 5000
  data:
    mongodb:
      uri: mongodb://localhost:27017/learning_community
      auto-index-creation: true
